### ISSUE TITLE
Create Support for gitlab integration

### ISSUE THREAD

**Issue by adnanhashmi09** [middlewarehq/middleware#455]
## Why do we need this ?
Currently we only have github support. We need to support gitlab integration as well. It has also been requested in #358. This issue will track all the subtask necessary for completely integrating gitlab. 

This effort will be considered complete when all the subtasks are completed.
## Subtask
Backend Efforts
- [x] #456 
- [x] #465
- [x] #460
- [x] #467
- [ ] Make API for getting all the opensource projects accessible through the PAT

Frontend Efforts
- [x] Add integration card, checks and validations for Gitlab integration
- [x] Remove hardcoded values of `Integrations.GITHUB` across the code-base
- [x] Create APIs for searching projects across Gitlab
- [x] Handle URL based searching in-case of repos/projects not found

**Comment by e-for-eshaan** [comment]
@adnanhashmi09 is this complete?

**Comment by adnanhashmi09** [comment]
> @adnanhashmi09 is this complete?

Nope, this issue will also include the frontend tasks. This issue shall be closed after the entire feature is completed. Backend + Frontend

**Comment by jayantbh** [comment]
Note: Gitlab integration is parked temporarily.

**Comment by e-for-eshaan** [comment]
Gitlab integration is comlete, woohoo 🎉
